name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"
  schedule:
    - cron: '3 3 * * 2'  # 3:03 AM, every Tuesday

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  macOS:
    name: ${{ matrix.platform }}
    runs-on: macos-12
    strategy:
      fail-fast: false
      matrix:
        platform:
          - macOS
          - iOS
    steps:
    - uses: actions/checkout@v2
    - uses: mxcl/xcodebuild@v1
      with:
        swift: ~5.6
        scheme: FoundationEncore
        platform: ${{ matrix.platform }}
  linux:
    runs-on: ubuntu-latest
    container: swift:5.6
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: swift test --parallel --sanitize=thread -Xswiftc -warnings-as-errors
